# Generated by Django 6.0.3 on 2026-03-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_alter_sitesetup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
